chain:
  bech32_prefix: cosmos
  modules: []

node:
  type: remote
  config:
    rpc:
      client_name: gaia
      address: http://node1:26657
      max_connections: 20
    grpc:
      address: node1:9090
      insecure: true

parsing:
  workers: 1
  start_height: 1
  average_block_time: 5s
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true

database:
  url: postgresql://bdjuno:bdjuno@postgres:5432/bdjuno?sslmode=disable&search_path=public
  max_open_connections: 1
  max_idle_connections: 1
  partition_size: 100000
  partition_batch: 1000
  ssl_mode_enable: "false"
  ssl_root_cert: ""
  ssl_cert: ""
  ssl_key: ""

logging:
  level: debug
  format: text

actions:
  host: 127.0.0.1
  port: 3000
