---
version: "3"
services:
  node1:
    image: asguardnetwork/spacefolders:assetmantle-0.3.1
    container_name: node1
    restart: always
    environment:
      - CHAIN_ID=load-test-1
    ports:
      - 26657
    volumes:
      - chain-data1:/root/node1/.mantleNode
      # - chain-data2:/root/node2/.mantleNode
      # - chain-data3:/root/node3/.mantleNode
    entrypoint: sh
    networks:
      - cosmos
    command:
      - -cex
      - |
        if [[ -f /root/node1/.mantleNode/config/genesis.json ]];
        then
          mantleNode --home /root/node1/.mantleNode start \
          --rpc.laddr=tcp://0.0.0.0:26657 &
          sleep 99999
        else
          mantleNode --home /root/node1/.mantleNode init test --chain-id $$CHAIN_ID
          mantleNode --home /root/node1/.mantleNode keys add test --keyring-backend test
          mantleNode --home /root/node1/.mantleNode add-genesis-account test 10000000000000000000000stake --keyring-backend test
          mantleNode --home /root/node1/.mantleNode gentx test 1000000000stake --keyring-backend test --chain-id $$CHAIN_ID
          mantleNode --home /root/node1/.mantleNode collect-gentxs
          sed -i 's%priv_validator_laddr =.*%priv_validator_laddr = "tcp://0.0.0.0:26658"%g' /root/node1/.mantleNode/config/config.toml
          sed -i '/^priv_validator_key_file =.*/ s/./#&/' /root/node1/.mantleNode/config/config.toml
          sed -i '/^priv_validator_state_file =.*/ s/./#&/' /root/node1/.mantleNode/config/config.toml
          sleep 30
        fi
        mantleNode --home /root/node1/.mantleNode start \
        --rpc.laddr=tcp://0.0.0.0:26657 &
        # putting sleep for debugging purpose
        sleep 99999

  node2:
    image: asguardnetwork/spacefolders:assetmantle-0.3.1
    container_name: node2
    restart: always
    environment:
      - CHAIN_ID=load-test-1
    volumes:
      - chain-data1:/root/node1/.mantleNode
      - chain-data2:/root/node2/.mantleNode
      - chain-data3:/root/node3/.mantleNode
    entrypoint: sh
    networks:
      - cosmos
    command:
      - -cex
      - |
        if [[ -f /root/node2/.mantleNode/config/genesis.json ]];
        then
          mantleNode --home /root/node2/.mantleNode start \
          --rpc.laddr=tcp://0.0.0.0:26657 &
          sleep 99999
        else
          mantleNode --home /root/node2/.mantleNode init test2 --chain-id $$CHAIN_ID
          mantleNode --home /root/node2/.mantleNode keys add test2 --keyring-backend test
          sleep 10
          sed -i 's/persistent_peers =.*/persistent_peers = "'$$(mantleNode --home /root/node1/.mantleNode tendermint show-node-id)@node1:26656,$$(mantleNode --home /root/node3/.mantleNode tendermint show-node-id)@node3:26656'"/g' /root/node2/.mantleNode/config/config.toml
          cat /root/node2/.mantleNode/config/config.toml | grep persistent_peers
          # sed -i "s/rpc_servers =.*/rpc_servers = "'"node1:26657,node1:26657"'"/g" /root/node2/.mantleNode/config/config.toml
          # cat /root/node2/.mantleNode/config/config.toml | grep rpc_servers
          cp /root/node1/.mantleNode/config/genesis.json /root/node2/.mantleNode/config/genesis.json
          sleep 30
        fi
        mantleNode --home /root/node2/.mantleNode start \
        --rpc.laddr=tcp://0.0.0.0:26657 &
        # putting sleep for debugging purpose
        sleep 99999

  node3:
    image: asguardnetwork/spacefolders:assetmantle-0.3.1
    container_name: node3
    restart: always
    environment:
      - CHAIN_ID=load-test-1
    volumes:
      - chain-data1:/root/node1/.mantleNode
      - chain-data2:/root/node2/.mantleNode
      - chain-data3:/root/node3/.mantleNode
    entrypoint: sh
    networks:
      - cosmos
    command:
      - -cex
      - |
        if [[ -f /root/node3/.mantleNode/config/genesis.json ]];
        then
          mantleNode --home /root/node3/.mantleNode start \
          --rpc.laddr=tcp://0.0.0.0:26657 &
          sleep 99999
        else
          mantleNode --home /root/node3/.mantleNode init test3 --chain-id $$CHAIN_ID
          mantleNode --home /root/node3/.mantleNode keys add test3 --keyring-backend test
          sleep 10
          sed -i 's/persistent_peers =.*/persistent_peers = "'$$(mantleNode --home /root/node1/.mantleNode tendermint show-node-id)@node1:26656,$$(mantleNode --home /root/node2/.mantleNode tendermint show-node-id)@node2:26656'"/g' /root/node3/.mantleNode/config/config.toml
          cat /root/node3/.mantleNode/config/config.toml | grep persistent_peers
          # sed -i "s/rpc_servers =.*/rpc_servers = "'"node1:26657,node1:26657"'"/g" /root/node3/.mantleNode/config/config.toml
          # cat /root/node3/.mantleNode/config/config.toml | grep rpc_servers
          cp /root/node1/.mantleNode/config/genesis.json /root/node3/.mantleNode/config/genesis.json
          sleep 30
        fi
        mantleNode --home /root/node3/.mantleNode start \
        --rpc.laddr=tcp://0.0.0.0:26657 &
        # putting sleep for debugging purpose
        sleep 99999

  signer1:
    image: shyamsv/tmkms:0.12.2-alpine-3.18.2
    container_name: signer1
    restart: always
    environment:
      - CHAIN_ID=load-test-1
    networks:
      - cosmos
    volumes:
      - signer-data1:/root/.tmkms
      - chain-data1:/root/node1/.mantleNode
    entrypoint: sh
    command:
      - -cex
      - |
        # running tmkms init to generate config
        tmkms init /root/.tmkms
        sleep 20

        # copy the private key from validator node to the tmkms container
        cp /root/node1/.mantleNode/config/priv_validator_key.json /root/.tmkms/secrets

        # update chain-id
        sed -i "s/cosmoshub-3/$$CHAIN_ID/g" /root/.tmkms/tmkms.toml

        # update protocol version
        sed -i 's/protocol_version =.*/protocol_version = "v0.34"/g' /root/.tmkms/tmkms.toml

        # update validator node address
        sed -i 's%addr =.*%addr = "tcp://node1:26658"%g' /root/.tmkms/tmkms.toml

        # importing validator node private key into softsign
        tmkms softsign import /root/.tmkms/secrets/priv_validator_key.json /root/.tmkms/secrets/$$CHAIN_ID-consensus.key

        # starting tmkms remote signer
        tmkms start --config /root/.tmkms/tmkms.toml

volumes:
  chain-data1:
  chain-data2:
  chain-data3:
  signer-data1:

networks:
  cosmos:
