version: '3.2'

services:
  node1:
    image: asguardnetwork/spacefolders:gaia-v10.0.1
    container_name: node1
    environment:
      - CHAIN_ID=load-test-1
      - NODE1_HOME=/root/node1/.gaia
    networks: &node-network
      - tenderduty-cosmos
    ports:
      - 26657
    volumes:
      - node1:/root/node1/.gaia
    entrypoint: sh
    command:
      - -cex
      - |
        if [[ -f $$NODE1_HOME/config/genesis.json ]];
        then
          gaiad --home $$NODE1_HOME init test --chain-id $$CHAIN_ID
          gaiad --home $$NODE1_HOME keys add test --keyring-backend test
          gaiad --home $$NODE1_HOME add-genesis-account test 10000000000000000000000stake --keyring-backend test
          gaiad --home $$NODE1_HOME gentx test 1000000000stake --keyring-backend test --chain-id $$CHAIN_ID
          gaiad --home $$NODE1_HOME collect-gentxs
        fi
        gaiad --home $$NODE1_HOME start --rpc.laddr=tcp://0.0.0.0:26657 &
        # putting sleep for debugging purpose
        sleep 99999

  tenderduty:
    image: ghcr.io/blockpane/tenderduty:v2.2.1
    container_name: tenderduty
    command: ""
    networks: *node-network
    ports:
      - "8888:8888" # Dashboard
      - "28686:28686" # Prometheus exporter
    volumes:
      - tenderduty_home:/var/lib/tenderduty
      - ./blockpane-tenderduty-config.yaml:/var/lib/tenderduty/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: unless-stopped

volumes:
  node1:
  tenderduty_home:

networks:
  tenderduty-cosmos:
